### ISSUE TITLE
plugin_factory.cpp: no member named 'instance' in namespace 'irods::client_api_allowlist'

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods_api_plugin_genquery2#60]
Building against tip of main produces the following error in `api_plugin/src/plugin_factory.cpp`:
```
/api_genquery2_source/api_plugin/src/plugin_factory.cpp:16:31: error: no member named 'instance' in namespace 'irods::client_api_allowlist'
        irods::client_api_allowlist::instance().add(IRODS_APN_GENQUERY2);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```

irods/irods@9d730928fcfa29d4a83f8d2f8d24890a242cf12a moved the cheese.

**Comment by SwooshyCueb** [comment]
Actually, it looks like there is an `#ifdef` that should be taking care of this already. This will likely be solved as part of #11

**Comment by korydraughn** [comment]
That's correct.

The dev has to tell the build system not to compile with 430 compatibility. The build option exists because tip of main reports as 4.3.0 still. Once we bump the iRODS version in irods/irods, we can set the build option automatically.

Were you thinking of handling it a different way?

**Comment by korydraughn** [comment]
Wow, I just realized this was closed.
