### ISSUE TITLE
Set default value for `IRODS_ENABLE_430_COMPATIBILITY` to `NO` once iRODS 4.3.1 is released

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_api_plugin_genquery2#64]
https://github.com/irods/irods_api_plugin_genquery2/blob/5793807178838b80f63dcccfbf280e4d7be8674e/CMakeLists.txt#L3

**Comment by SwooshyCueb** [comment]
I'd rather remove this entirely and replace the precompiler conditionals with version checks

**Comment by korydraughn** [comment]
Even better.

**Comment by SwooshyCueb** [comment]
Given that building against 4.3.0 is *already* broken, as we include `IrodsRunpathDefaults` (not introduced until after 4.3.0) in `CMakeLists.txt`, and will be *further* broken once my PR for irods/irods#7312 lands, perhaps we should rip out all the 4.3.0 stuff instead of trying to maintain compatibility.

**Comment by korydraughn** [comment]
I wasn't aware we broke support for 4.3.0. That was not intended. We want 4.3.0 users to be able to compile the project and play with it.

Looking at the commit that introduces `IrodsRunpathDefaults`, it seems we can add a simple conditional that restores support. Does it require more work than that?

I think we have to support 4.3.0 until we decide the experimental period is over.

**Comment by SwooshyCueb** [comment]
A conditional would work fine.
